# SPDX-License-Identifier: GPL-2.0-only
obj-y			+= kernel/ mm/ net/
obj-$(CONFIG_KVM)	+= kvm/
obj-$(CONFIG_XEN)	+= xen/
obj-$(CONFIG_MUEN_GUEST)	+= muen/
obj-$(subst m,y,$(CONFIG_HYPERV))	+= hyperv/
obj-$(CONFIG_CRYPTO)	+= crypto/

# for cleaning
subdir- += boot
