#define NLTYPE_MUENNET_NAME "muennet"

enum {
	MUENNET_C_UNSPEC,
	MUENNET_C_ADD_CHILD,
	MUENNET_C_DEL_CHILD,
	MUENNET_C_ADD_MARK,
	MUENNET_C_DEL_MARK,
	__MUENNET_C_MAX,
};

enum {
	MUENNET_A_UNSPEC,
	MUENNET_A_DEV,
	MUENNET_A_CHILD_DEV,
	MUENNET_A_MARK,
	__MUENNET_A_MAX,
};
#define MUENNET_A_MAX (__MUENNET_A_MAX - 1)
