obj-$(CONFIG_MUEN_CHANNEL)	+= channel/
obj-$(CONFIG_MUEN_SINFO)	+= sinfo/
obj-$(CONFIG_MUEN_CLKSRC)	+= clksrc/
obj-$(CONFIG_MUEN_PCI)		+= pci/
obj-$(CONFIG_MUEN_INPUT)	+= input/
obj-$(CONFIG_MUEN_SMP)		+= smp/
